version: '3.8'
volumes:
  postgres_data:
      driver: local
  mongo_data:
      driver: local
services:
  rabbitmq3:
      container_name: "rabbitmq"
      image: rabbitmq:3.8-management-alpine
      restart: unless-stopped
      environment:
        - RABBITMQ_DEFAULT_USER=jovicdev
        - RABBITMQ_DEFAULT_PASS=root
      ports:
        - 5672:5672
        - 15672:15672
  postgres:
      image: postgres
      container_name: postgresdb
      restart: unless-stopped
      volumes:
        - postgres_data:/data/db
      environment:
        POSTGRES_DB: user-management
        POSTGRES_USER: jovicdev
        POSTGRES_PASSWORD: root
      ports:
        - 5432:5432
  mongodb:
      image: mongo
      container_name: mongodb
      restart: unless-stopped
      environment:
        MONGO_INITDB_ROOT_USERNAME: jovicdev
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - 27017:27017
      volumes:
        - mongo_data:/data/db
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: keycloak
      restart: unless-stopped
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: user-management
        DB_USER: jovicdev
        DB_SCHEMA: public
        DB_PASSWORD: root
        KEYCLOAK_USER: jovicdev
        KEYCLOAK_PASSWORD: root
        KC_HTTPS_CERTIFICATE_FILE: /root/revenue-collection/microservices/base-services/server.crt.pem
        KC_HTTPS_CERTIFICATE_KEY_FILE: /root/revenue-collection/microservices/base-services/server.key.pem
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8443:8443
      depends_on:
        - postgres
      volumes:
        - $PWD/server.crt.pem:/root/revenue-collection/microservices/base-services/server.crt.pem
        - $PWD/server.key.pem:/root/revenue-collection/microservices/base-services/server.key.pem